services:
  backend:
    image: backend
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
